In [11]:
import torch

In [12]:
scalar = torch.tensor(611)
scalar
##how to make a tensor

tensor(611)

In [13]:
scalar.ndim
#its a single number here

0

In [14]:
 scalar.item()
 #get tensor back as python int

611

In [15]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [16]:
vector.ndim

1

In [17]:
vector.shape

torch.Size([2])

In [18]:
#MATRIX
MATRIX = torch.tensor([[7,8]
                      ,[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [19]:
MATRIX.ndim

2

In [20]:
MATRIX[1]

tensor([ 9, 10])

In [21]:
MATRIX.shape

torch.Size([2, 2])

In [22]:
#tensor
TENSOR =torch.tensor([[[1,2,3]
                       ,[4,5,6]
                       ,[6,7,8]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]]])

In [23]:
TENSOR.ndim

3

In [24]:
TENSOR.shape

torch.Size([1, 3, 3])

In [25]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]])

Random tensor


why random tensor   
genreally start with random number tensor then aadjust themself as per data in a neural netwwork




start with random numbers -look at the data ->update random number->look data -->update again

In [26]:
#create  random tensor of size
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3288, 0.0318, 0.8243, 0.7377],
        [0.2337, 0.1060, 0.7466, 0.3177],
        [0.8953, 0.9065, 0.9578, 0.8006]])

In [27]:
random_tensor.ndim

2

In [28]:
#CREATE RANDOM TENSOR WITH SIMILAR SHAPE TO AN IMGE TENSOR
random_image_tensor= torch.rand(size=(224,224,3))#height width ccolor channel (R,G,B)
random_image_tensor.shape, random_image_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [29]:
torch.rand(3,3)

tensor([[0.3867, 0.6544, 0.8866],
        [0.5569, 0.6501, 0.2976],
        [0.4382, 0.0459, 0.1654]])

In [30]:
#create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
ones.dtype

torch.float32

In [34]:
random_tensor.dtype

torch.float32

In [35]:
##creating tensor in range



using torch.range


In [36]:
torch.range(0,10)

/tmp/ipykernel_8119/497691777.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [37]:
torch.__version__

'2.10.0+cpu'

In [38]:
onetoten=torch.arange(0,10)
onetoten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
onetoten=torch.arange(start=0,end=1000,step=77)
onetoten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [40]:
#creating tensor like
tezeros= torch.zeros_like(input=onetoten)
tezeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
#float 32 tensor
float32=torch.tensor([3.0,4.0,5.0],
                     dtype=torch.float32,#what datatype is your tenso
                     device=None,#what device is your tennsor on
                     requires_grad=False#wheather or not to track gradients witth this tensor operations
                     )
float32

tensor([3., 4., 5.])

In [42]:
float32.dtype

torch.float32

In [43]:
float16=float32.type(torch.float16)
float16

tensor([3., 4., 5.], dtype=torch.float16)

In [44]:
float16*float32

tensor([ 9., 16., 25.])

In [45]:
int32=torch.tensor([4,5,6],
                     dtype=torch.int64,#what datatype is your tenso
                     device=None,#what device is your tennsor on
                     requires_grad=False#wheather or not to track gradients witth this tensor operations
                     )
int32

tensor([4, 5, 6])

In [46]:
int32*float32

tensor([12., 20., 30.])

In [47]:
int32.dtype

torch.int64

In [48]:
sometensor=torch.rand([3,4])
sometensor

tensor([[0.5213, 0.8725, 0.3548, 0.2354],
        [0.8822, 0.0615, 0.0222, 0.8650],
        [0.1364, 0.3466, 0.1688, 0.6261]])

In [49]:
sometensor.dtype

torch.float32

In [50]:
print(sometensor)
print(f"datatype of tensor:{sometensor.dtype}")
print(f"shape of tensor:{sometensor.shape}")
print(f"device of tensor:{sometensor.device}")


tensor([[0.5213, 0.8725, 0.3548, 0.2354],
        [0.8822, 0.0615, 0.0222, 0.8650],
        [0.1364, 0.3466, 0.1688, 0.6261]])
datatype of tensor:torch.float32
shape of tensor:torch.Size([3, 4])
device of tensor:cpu


In [51]:
#tensor operations
# tensor operatrions includes addition subtraction multiplication
# division
# matrricx multiplications


In [52]:
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [53]:
tensor1=torch.tensor([10,19,223])
tensor1*8

tensor([  80,  152, 1784])

In [54]:
tensor1-tensor


tensor([  9,  17, 220])

In [55]:
tensor-1


tensor([0, 1, 2])

In [56]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [57]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [58]:
##Matric multipliacation
# element wise multinomial
# matrix multiplication (dot product)  2 matricx will multiply through dot product here

In [59]:
tensor*tensor

tensor([1, 4, 9])

In [60]:
print(tensor,"*",tensor)
print (f"equals:{tensor*tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
equals:tensor([1, 4, 9])


In [61]:
torch.matmul(tensor,tensor)

tensor(14)

In [62]:
## sum  of the resultant is added in here

In [63]:
tensor


tensor([1, 2, 3])

In [64]:
1*1+2*2+3*3


14

In [65]:
%%time
value=0
for i in range (len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)


tensor(14)
CPU times: user 1.95 ms, sys: 151 µs, total: 2.11 ms
Wall time: 2.79 ms


In [66]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 531 µs, sys: 0 ns, total: 531 µs
Wall time: 546 µs


tensor(14)

In [67]:
#better inbuild function in here

In [68]:
#in matrix multiplication the inner dimention must match
# (3,2) @ (3,2)wont work
# (2,3) @(3,2)   works

In [69]:
tensor@tensor

tensor(14)

In [70]:
torch.matmul(torch.rand(3,2),torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [71]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.5216, 0.7773, 1.2334],
        [0.1347, 0.6185, 0.6889],
        [0.2929, 0.8908, 1.0953]])

In [72]:
#resulting matrix has shape of the outer dimentions

In [73]:
torch.matmul(torch.rand(7,6),torch.rand(6,7))

tensor([[1.4299, 1.3318, 1.8047, 1.5469, 1.0489, 1.1238, 2.0121],
        [2.0107, 1.4954, 2.0668, 1.9392, 1.5049, 1.5590, 2.1447],
        [1.0878, 0.8552, 1.2071, 1.1716, 0.4764, 0.8365, 1.5986],
        [1.2011, 1.2545, 1.5270, 1.4107, 1.1709, 0.9325, 1.4899],
        [1.1362, 1.5506, 1.6059, 1.4636, 1.0882, 0.9081, 1.4864],
        [1.6035, 1.5105, 1.8845, 1.8601, 1.3385, 1.1669, 1.9470],
        [1.7152, 1.7658, 2.0878, 1.7538, 1.1424, 1.3747, 2.1185]])

In [74]:
#shapes for matrix multiplication
tensor_a=torch.tensor([[1,2],
                      [3,4],
                      [5,6]])
tensor_b= torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
torch.matmul(tensor_a,tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [75]:
tensor_a.shape,tensor_b.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

**transpose** witches the axes or simentions of a given tensor

In [76]:
tensor_b.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [77]:
torch.matmul(tensor_a,tensor_b.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [78]:
#finding the min max  mean sunm of tensor aggregation here

In [79]:
a=torch.arange(0,100,10)
a
a.dtype

torch.int64

In [80]:
torch.min(a),a.min()


(tensor(0), tensor(0))

In [81]:
torch.max(a)

tensor(90)

In [82]:
torch.mean(a.type(torch.float32)), a.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [83]:
torch.sum(a),a.sum()

(tensor(450), tensor(450))

In [84]:
##finding postional min and max

In [85]:
a.argmin()

tensor(0)

In [86]:
a.argmax()

tensor(9)

In [87]:
a[9]

tensor(90)

In [88]:
a

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

##RESHAPING STACKING SQUEZZING AND UNSQUEZZING TENSORS
*RESHAPING -SHAPES AN INPUT TENSORS ON YOP OF CERTAIN SHAPE BUT KEEP THE SAME MEMORY AS THE ORIGNAL TENSOR
*STACKING -COMBINNING MULTIPLE TENSORS  ON TOP OF EACH OTHER(VSTACK)
*SQUEEZE -REMOVES '1 DIMENTIONS FROM A TENSOR
*UNSQUEEZE -ADD ONE DIMENTION TO THE TARGET HERE
*PERMUTE-RETURN A VIEW OF THE INPUT WITH DIMENTIONS PERMUTED (SWAPPED) IN A CERTAIN WAY

In [89]:
import torch
x=torch.arange(1.,13.)
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [90]:
y=torch.arange(1.,13.)
y,y.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [91]:
y=y.reshape(6,2)

In [92]:
xreshape=x.reshape(1,9)

RuntimeError: shape '[1, 9]' is invalid for input of size 12

In [94]:
#add an extra dimention here
x=x.reshape(6,2)
x


tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])

In [95]:
#CHNAGE THE VIEW
z=x.view(6,2)
z,z.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]),
 torch.Size([6, 2]))

In [96]:
##changing z xhnages the x here cause tensor shares the same memory as the x here
z[:,0] =0
z,x

(tensor([[ 0.,  2.],
         [ 0.,  4.],
         [ 0.,  6.],
         [ 0.,  8.],
         [ 0., 10.],
         [ 0., 12.]]),
 tensor([[ 0.,  2.],
         [ 0.,  4.],
         [ 0.,  6.],
         [ 0.,  8.],
         [ 0., 10.],
         [ 0., 12.]]))

In [97]:
z[0,:] =9
z,x

(tensor([[ 9.,  9.],
         [ 0.,  4.],
         [ 0.,  6.],
         [ 0.,  8.],
         [ 0., 10.],
         [ 0., 12.]]),
 tensor([[ 9.,  9.],
         [ 0.,  4.],
         [ 0.,  6.],
         [ 0.,  8.],
         [ 0., 10.],
         [ 0., 12.]]))

In [98]:
xstacked=torch.stack([x,y,x,x],dim=2)
xstacked

tensor([[[ 9.,  1.,  9.,  9.],
         [ 9.,  2.,  9.,  9.]],

        [[ 0.,  3.,  0.,  0.],
         [ 4.,  4.,  4.,  4.]],

        [[ 0.,  5.,  0.,  0.],
         [ 6.,  6.,  6.,  6.]],

        [[ 0.,  7.,  0.,  0.],
         [ 8.,  8.,  8.,  8.]],

        [[ 0.,  9.,  0.,  0.],
         [10., 10., 10., 10.]],

        [[ 0., 11.,  0.,  0.],
         [12., 12., 12., 12.]]])

In [99]:
xreshape=x.reshape(1,12)
xreshape

tensor([[ 9.,  9.,  0.,  4.,  0.,  6.,  0.,  8.,  0., 10.,  0., 12.]])

In [100]:
print(f"\n previous tensor:{xreshape}")
print(f"previous shape:{xreshape.shape}")

xsqueeze=xreshape.squeeze()
print(f"\n new tensor:{xsqueeze}")
print(f"new shape:{xsqueeze.shape}")


 previous tensor:tensor([[ 9.,  9.,  0.,  4.,  0.,  6.,  0.,  8.,  0., 10.,  0., 12.]])
previous shape:torch.Size([1, 12])

 new tensor:tensor([ 9.,  9.,  0.,  4.,  0.,  6.,  0.,  8.,  0., 10.,  0., 12.])
new shape:torch.Size([12])


In [101]:
## TOCH UNSQUEEZE ADD ONE MORE DIMENTION TO A TARGET TENSOR
xunsqueeze=xreshape.unsqueeze(dim=1)
xunsqueeze , xunsqueeze.shape

(tensor([[[ 9.,  9.,  0.,  4.,  0.,  6.,  0.,  8.,  0., 10.,  0., 12.]]]),
 torch.Size([1, 1, 12]))

In [102]:
# additional on r more dimention here

In [103]:
#commute torch.commute -rearranges  thr dimention of a tensor in a specified order here

In [104]:
nz= torch.rand(3,4,6,7,8,3,3,32,2)
torch.permute(nz,(1,2,0,3,4,5,6,7,8)).size()

torch.Size([4, 6, 3, 7, 8, 3, 3, 32, 2])

In [105]:
xorignal=torch.rand(224,224,3)
print (f"original size:{xorignal}")
xorignal.shape
#permute
xpermute= torch.permute(xorignal,(2,0,1))
print(f"final permute value is \n{xpermute}")
xpermute.shape
xorignal.shape

original size:tensor([[[0.7641, 0.7717, 0.7941],
         [0.7038, 0.3075, 0.1555],
         [0.3520, 0.2685, 0.3318],
         ...,
         [0.0582, 0.5629, 0.4072],
         [0.2713, 0.7101, 0.8816],
         [0.1987, 0.2615, 0.5442]],

        [[0.7758, 0.3275, 0.1305],
         [0.1317, 0.2334, 0.3559],
         [0.6001, 0.5008, 0.6174],
         ...,
         [0.8884, 0.7791, 0.6473],
         [0.1411, 0.9298, 0.7520],
         [0.1182, 0.6076, 0.0412]],

        [[0.5652, 0.1136, 0.7443],
         [0.8923, 0.6181, 0.0011],
         [0.0898, 0.0148, 0.4544],
         ...,
         [0.9027, 0.2859, 0.8243],
         [0.6839, 0.7737, 0.7326],
         [0.7313, 0.4551, 0.5846]],

        ...,

        [[0.0278, 0.6757, 0.3131],
         [0.3693, 0.7028, 0.3676],
         [0.7275, 0.6441, 0.6166],
         ...,
         [0.8500, 0.2721, 0.9617],
         [0.0072, 0.2273, 0.4159],
         [0.2068, 0.1328, 0.2049]],

        [[0.3451, 0.0833, 0.2191],
         [0.9914, 0.4204, 0.0968]

torch.Size([224, 224, 3])

In [109]:
xorignal[0,0,0] =728218
xorignal[0,0,0] ,xpermute[0,0,0]

(tensor(728218.), tensor(728218.))

In [ ]:
##INDEXING (SELECTING DATA FROM TENSORS )

In [112]:
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [113]:
#index new tensor here
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [123]:
x[0][1][1]

tensor(5)

In [124]:
#get all values of  0th and first dimentions but index 1st and 2nsd element
x[:,:,1]

tensor([[2, 5, 8]])

In [125]:
#get all values of the o dimention but onlu the 1 index of  value of 1 st and 2nd simention here
x[:,1,1]

tensor([5])

In [127]:
#O OF OTH AND ALL VALUE OF 2ND
x[0,0,:]

tensor([1, 2, 3])

In [128]:
x


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [129]:
x[:,:,2]

tensor([[3, 6, 9]])

In [130]:
# # ## pytorch tensor and numy
# # pytorch has fubnctionality to interact with numpy here

# *data in numpy,want in Pytorch tensor-> torch.from_numpy(ndarray)
# *pytorch tensor_> Numpy-> torch.Tensor.numpy()

# # ## pytorch tensor and numy
# # pytorch has fubnctionality to interact with numpy here

# *data in numpy,want in Pytorch tensor-> torch.from_numpy(ndarray)
# *pytorch tensor_> Numpy-> torch.Tensor.numpy()

In [140]:
import torch
import numpy as np
array =np.arange(1.0,8.0)
tensor=torch.from_numpy(array).type(torch.float32)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [133]:
array.dtype

dtype('float64')

In [136]:
s=torch.arange(1,9)
s,s.dtype

(tensor([1, 2, 3, 4, 5, 6, 7, 8]), torch.int64)

In [141]:
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [161]:
#tensor to numpy array
tensor=torch.ones(7)
# tensor=tensor.reshape(7,1)
numpytensor=tensor.numpy()
tensor,numpytensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [162]:
tensor=tensor+1
tensor,numpytensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [165]:
# #reproducability (trying to make random out of random in here )
# start with random number -> tensor operations ->update random number here ->
# try and make better production of data ->again and again


# to reduce the randomness in NN and pytorch comes the concept of random seed
# seed does is flovour randomness


In [177]:
import torch
a=torch.rand(3,4)
b=torch.rand(3,4)
print(a)
print(b)
print(a==b)

tensor([[0.4341, 0.8254, 0.4384, 0.8871],
        [0.0080, 0.8342, 0.0580, 0.5640],
        [0.2132, 0.5233, 0.8004, 0.9779]])
tensor([[0.8205, 0.7524, 0.5720, 0.1215],
        [0.9439, 0.4788, 0.0897, 0.8329],
        [0.7380, 0.6058, 0.9029, 0.8205]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [183]:
import torch
RANDOM=42
torch.manual_seed(RANDOM)
c=torch.rand(3,4)
torch.manual_seed(RANDOM)
d=torch.rand(3,4)

print(c)
print(d)
print(c==d)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [185]:
import torch
RANDOM=42
torch.manual_seed(RANDOM)
c=torch.rand(3,4)
c

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [ ]:
##the fuck itsb the same here

In [ ]:
##run tensor  and pytorch on gpu
# gpu= faster computation on number +cuda+nvidia hardware (good)

In [ ]:
##getting a gpu use google collab for free or go for pro here

In [2]:
!nvidia-smi

Wed May 20 19:42:02 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   41C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [6]:
## check for gpu acces with pytorch
import torch
torch.cuda.is_available()

True

In [8]:
##setup device agnostic code
device ="cuda" if torch.cuda.is_available() else cuda
device

'cuda'

In [9]:
torch.cuda.device_count()

1

In [10]:
#putting tensors (and models ) on gpu

In [ ]:
# we want gpu is faster  computations here

In [13]:
tensor=torch.tensor([1,2,3])
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [17]:
#move tensor to gpu if available here
tensortogpu=tensor.to(device)
tensortogpu


tensor([1, 2, 3], device='cuda:0')

In [22]:
## move tensor back to cpu


In [27]:
# case 1 if tensor on gpu cant transform it to numpy  here
tensortogpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [31]:
#to fix the tensor with numpy here
tensobacktocpu=tensortogpu.cpu()
tensobacktocpu

tensor([1, 2, 3])

In [32]:
tensortogpu

tensor([1, 2, 3], device='cuda:0')